<?php

// namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
// use Illuminate\Database\Seeder;
// use Illuminate\Support\Facades\DB;

// class CitySeeder extends Seeder
// {
//     /**
//      * Run the database seeds.
//      */
//     public function run(): void
//     {
//         //
//         DB::table('cities')->delete();
//         $cities = array(

//  array('name' => "Aryanah", 'state_id' => 1),
//             array('name' => "Bordj Aalouine", 'state_id' => 1),
//             array('name' => "Burj-al-'Amri", 'state_id' => 1),
//             array('name' => "La Soukra", 'state_id' => 1),
//             array('name' => "Qal'at-al-Andalus", 'state_id' => 1),
//             array('name' => "Sidi Thabit", 'state_id' => 1),
//             array('name' => "Taburbah", 'state_id' => 1),
//             array('name' => "Wadi al-Layl", 'state_id' => 1),
//             array('name' => "ad-Dandan", 'state_id' => 1),
//             array('name' => "al-Battan", 'state_id' => 1),
//             array('name' => "al-Jadidah", 'state_id' => 1),
//             array('name' => "al-Murnaqiyah", 'state_id' => 1),
//             array('name' => "at-Tadaman Dawwar Hishar", 'state_id' => 1),
//             array('name' => "Bajah", 'state_id' => 2),
//             array('name' => "Majaz-al-Bab", 'state_id' => 2),
//             array('name' => "Nafzah", 'state_id' => 2),
//             array('name' => "Quballat", 'state_id' => 2),
//             array('name' => "Tabursuq", 'state_id' => 2),
//             array('name' => "Tastur", 'state_id' => 2),
//             array('name' => "Zahrat Madina", 'state_id' => 2),
//             array('name' => "al-Ma'qulah", 'state_id' => 2),
//             array('name' => "'Awsajah", 'state_id' => 3),
//             array('name' => "Binzart", 'state_id' => 3),
//             array('name' => "Ghar-al-Milh", 'state_id' => 3),
//             array('name' => "Manzil 'Abd-ar-Rahman", 'state_id' => 3),
//             array('name' => "Manzil Bu Ruqaybah", 'state_id' => 3),
//             array('name' => "Manzil Jamil", 'state_id' => 3),
//             array('name' => "Matir", 'state_id' => 3),
//             array('name' => "Rafraf", 'state_id' => 3),
//             array('name' => "Ras-al-Jabal", 'state_id' => 3),
//             array('name' => "Sajanan", 'state_id' => 3),
//             array('name' => "Tinjah", 'state_id' => 3),
//             array('name' => "al-'Aliyah", 'state_id' => 3),
//             array('name' => "al-Matlin", 'state_id' => 3),
//             array('name' => "'Ayn Darahim", 'state_id' => 4),
//             array('name' => "Bani Matir", 'state_id' => 4),
//             array('name' => "Bu Salim", 'state_id' => 4),
//             array('name' => "Firnanah", 'state_id' => 4),
//             array('name' => "Ghar-ad-Dima'", 'state_id' => 4),
//             array('name' => "Jundubah", 'state_id' => 4),
//             array('name' => "Tabarqah", 'state_id' => 4),
//             array('name' => "Wadi Maliz", 'state_id' => 4),
//             array('name' => "Bani Khaddash", 'state_id' => 5),
//             array('name' => "Bin Qirdan", 'state_id' => 5),
//             array('name' => "Jarbah Ajim", 'state_id' => 5),
//             array('name' => "Jarbah Hawmat-as-Suq", 'state_id' => 5),
//             array('name' => "Jarbah Midun", 'state_id' => 5),
//             array('name' => "Jarjis", 'state_id' => 5),
//             array('name' => "Madaniyin", 'state_id' => 5),
//             array('name' => "Manubah", 'state_id' => 6),
//             array('name' => "Monastir", 'state_id' => 7),
//             array('name' => "Azimur", 'state_id' => 6),
//             array('name' => "Bani Hiyar", 'state_id' => 6),
//             array('name' => "Bani Khallad", 'state_id' => 6),
//             array('name' => "Bu 'Urqub", 'state_id' => 6),
//             array('name' => "Dar 'Alush", 'state_id' => 6),
//             array('name' => "Dar Sha'ban", 'state_id' => 6),
//             array('name' => "Hammam-al-Aghzaz", 'state_id' => 6),
//             array('name' => "Manzil Bu Zalafah", 'state_id' => 6),
//             array('name' => "Manzil Hurr", 'state_id' => 6),
//             array('name' => "Manzil Tamim", 'state_id' => 6),
//             array('name' => "Nabul", 'state_id' => 6),
//             array('name' => "Qalibiyah", 'state_id' => 6),
//             array('name' => "Qurbah", 'state_id' => 6),
//             array('name' => "Qurbus", 'state_id' => 6),
//             array('name' => "Qurunbaliyah", 'state_id' => 6),
//             array('name' => "Sulayman", 'state_id' => 6),
//             array('name' => "Taklisah", 'state_id' => 6),
//             array('name' => "Tazirkah", 'state_id' => 6),
//             array('name' => "Zawiyat-al-Jadidi", 'state_id' => 6),
//             array('name' => "al-Hammamat", 'state_id' => 6),
//             array('name' => "al-Huwariyah", 'state_id' => 6),
//             array('name' => "al-Ma'murah", 'state_id' => 6),
//             array('name' => "al-Middah", 'state_id' => 6),
//             array('name' => "as-Sama'ah", 'state_id' => 6),
//             array('name' => "Ghannush", 'state_id' => 7),
//             array('name' => "Marath", 'state_id' => 7),
//             array('name' => "Matmatat-al-Jadidah", 'state_id' => 7),
//             array('name' => "Matmatat-al-Qadimah", 'state_id' => 7),
//             array('name' => "Qabis", 'state_id' => 7),
//             array('name' => "Sanini an-Nahal", 'state_id' => 7),
//             array('name' => "Wadhraf", 'state_id' => 7),
//             array('name' => "al-Hammah", 'state_id' => 7),
//             array('name' => "al-Matwiyah", 'state_id' => 7),
//             array('name' => "az-Zarat", 'state_id' => 7),
//             array('name' => "Qafsah", 'state_id' => 8),
//             array('name' => "Umm-al-'Arais", 'state_id' => 8),
//             array('name' => "al-Madilah", 'state_id' => 8),
//             array('name' => "al-Mitlawi", 'state_id' => 8),
//             array('name' => "al-Qasr", 'state_id' => 8),
//             array('name' => "al-Qatar", 'state_id' => 8),
//             array('name' => "ar-Rudayyif", 'state_id' => 8),
//             array('name' => "as-Sanad", 'state_id' => 8),
//             array('name' => "Duz", 'state_id' => 9),
//             array('name' => "Jamnah", 'state_id' => 9),
//             array('name' => "Qibili", 'state_id' => 9),
//             array('name' => "Suq-al-Ahad", 'state_id' => 9),
//             array('name' => "al-Qal'ah", 'state_id' => 9),
//             array('name' => "'Aqarib", 'state_id' => 17),
//             array('name' => "Bi'r Ali Bin Khalifah", 'state_id' => 17),
//             array('name' => "Jabinyanah", 'state_id' => 17),
//             array('name' => "Manzil Shakir", 'state_id' => 17),
//             array('name' => "Qarmadah", 'state_id' => 17),
//             array('name' => "Qarqannah", 'state_id' => 17),
//             array('name' => "Safaqis", 'state_id' => 17),
//             array('name' => "Saqiyat-ad-Dair", 'state_id' => 17),
//             array('name' => "Saqiyat-az-Zayt", 'state_id' => 17),
//             array('name' => "Sfax", 'state_id' => 17),
//             array('name' => "Tinah", 'state_id' => 17),
//             array('name' => "al-'Ayn", 'state_id' => 17),
//             array('name' => "al-Hanashah", 'state_id' => 17),
//             array('name' => "al-Mahras", 'state_id' => 17),
//             array('name' => "as-Sukhayrah", 'state_id' => 17),
//             array('name' => "ash-Shayhiyah", 'state_id' => 17),
//             array('name' => "Sfax", 'state_id' => 18),
//             array('name' => "Barqu", 'state_id' => 19),
//             array('name' => "Bu 'Aradah", 'state_id' => 19),
//             array('name' => "Bu Ruwis", 'state_id' => 19),
//             array('name' => "Kasra", 'state_id' => 19),
//             array('name' => "Makthar", 'state_id' => 19),
//             array('name' => "Qa'afur", 'state_id' => 19),
//             array('name' => "Silyanah", 'state_id' => 19),
//             array('name' => "al-'Arusah", 'state_id' => 19),
//             array('name' => "al-Karib", 'state_id' => 19),
//             array('name' => "ar-Rawhiyah", 'state_id' => 19),
//             array('name' => "Akkudah", 'state_id' => 20),
//             array('name' => "Bu Fishah", 'state_id' => 20),
//             array('name' => "Hammam Susah", 'state_id' => 20),
//             array('name' => "Harqalah", 'state_id' => 20),
//             array('name' => "Masakin", 'state_id' => 20),
//             array('name' => "Qusaybat-ath-Thurayat", 'state_id' => 20),
//             array('name' => "Sidi Bu 'Ali", 'state_id' => 20),
//             array('name' => "Sidi al-Hani", 'state_id' => 20),
//             array('name' => "Susah", 'state_id' => 20),
//             array('name' => "Zawiyat Susah", 'state_id' => 20),
//             array('name' => "al-Masa'din", 'state_id' => 20),
//             array('name' => "al-Qal'at-al-Kabirah", 'state_id' => 20),
//             array('name' => "al-Qal'at-as-Saghirah", 'state_id' => 20),
//             array('name' => "an-Nafidah", 'state_id' => 20),
//             array('name' => "az-Zuhur", 'state_id' => 20),
//             array('name' => "Bi'r-al-Ahmar", 'state_id' => 21),
//             array('name' => "Dhahibah", 'state_id' => 21),
//             array('name' => "Ghumrassin", 'state_id' => 21),
//             array('name' => "Rimadah", 'state_id' => 21),
//             array('name' => "Tatawin", 'state_id' => 21),
//             array('name' => "Daqash", 'state_id' => 22),
//             array('name' => "Hammat-al-Jarid", 'state_id' => 22),
//             array('name' => "Naftah", 'state_id' => 22),
//             array('name' => "Tamaghzah", 'state_id' => 22),
//             array('name' => "Tawzar", 'state_id' => 22),
//             array('name' => "Bardaw", 'state_id' => 24),
//             array('name' => "Ben Arous", 'state_id' => 24),
//             array('name' => "Carthage", 'state_id' => 24),
//             array('name' => "Halq-al-Wadi", 'state_id' => 24),
//             array('name' => "Megrine", 'state_id' => 24),
//             array('name' => "Qartaj", 'state_id' => 24),
//             array('name' => "Sidi Bu Sa'id", 'state_id' => 24),
//             array('name' => "Tunis", 'state_id' => 24),
//             array('name' => "al-Marsa", 'state_id' => 24),
//             array('name' => "Bi'r Mashariqah", 'state_id' => 12),
//             array('name' => "Jabal-al-Wust", 'state_id' => 12),
//             array('name' => "Zaghwan", 'state_id' => 12),
//             array('name' => "al-Fahs", 'state_id' => 12),
//             array('name' => "an-Nazur", 'state_id' => 12),
//             array('name' => "az-Zaribah", 'state_id' => 12),
//             array('name' => "Manzil Salim", 'state_id' => 15),
//             array('name' => "Nibbar", 'state_id' => 15),
//             array('name' => "Qal'at-as-Sanan", 'state_id' => 15),
//             array('name' => "Saqiyat Sidi Yussuf", 'state_id' => 15),
//             array('name' => "Tajarwin", 'state_id' => 15),
//             array('name' => "ad-Dahmani", 'state_id' => 15),
//             array('name' => "al-Jarissah", 'state_id' => 15),
//             array('name' => "al-Kaf", 'state_id' => 15),
//             array('name' => "al-Qal'at-al-Khasba'", 'state_id' => 15),
//             array('name' => "al-Qusur", 'state_id' => 15),
//             array('name' => "as-Sars", 'state_id' => 15),
//             array('name' => "at-Tawiraf", 'state_id' => 15),
//             array('name' => "Awlad ash-Shamakh", 'state_id' => 14),
//             array('name' => "Bumirdas", 'state_id' => 14),
//             array('name' => "Habirah", 'state_id' => 14),
//             array('name' => "Karkar", 'state_id' => 14),
//             array('name' => "Mallulash", 'state_id' => 14),
//             array('name' => "Qusur-as-Saf", 'state_id' => 14),
//             array('name' => "Rajish", 'state_id' => 14),
//             array('name' => "Shurban", 'state_id' => 14),
//             array('name' => "Sidi 'Ulwan", 'state_id' => 14),
//             array('name' => "al-Baradi'ah", 'state_id' => 14),
//             array('name' => "al-Jamm", 'state_id' => 14),
//             array('name' => "al-Mahdiyah", 'state_id' => 14),
//             array('name' => "as-Sawasi", 'state_id' => 14),
//             array('name' => "ash-Shabbah", 'state_id' => 14),
//             array('name' => "'Amirat-al-Fahul", 'state_id' => 13),
//             array('name' => "'Amirat-al-Hajjaj", 'state_id' => 13),
//             array('name' => "'Amirat-at-Tawazarah", 'state_id' => 13),
//             array('name' => "Banan Budar", 'state_id' => 13),
//             array('name' => "Banblat wal-Manarah", 'state_id' => 13),
//             array('name' => "Bani Hassan", 'state_id' => 13),
//             array('name' => "Bu Hajjar", 'state_id' => 13),
//             array('name' => "Ghanadah", 'state_id' => 13),
//             array('name' => "Jammal", 'state_id' => 13),
//             array('name' => "Khunays", 'state_id' => 13),
//             array('name' => "Lamtah", 'state_id' => 13),
//             array('name' => "Manzil Farsi", 'state_id' => 13),
//             array('name' => "Manzil Hayah", 'state_id' => 13),
//             array('name' => "Manzil Kamil", 'state_id' => 13),
//             array('name' => "Manzil Nur", 'state_id' => 13),
//             array('name' => "Qasr Hallal", 'state_id' => 13),
//             array('name' => "Qusaybat-al-Madyuni", 'state_id' => 13),
//             array('name' => "Sahilin Ma'atmar", 'state_id' => 13),
//             array('name' => "Sayyadah", 'state_id' => 13),
//             array('name' => "Sidi 'Amara", 'state_id' => 13),
//             array('name' => "Sidi Bin Nur", 'state_id' => 13),
//             array('name' => "Tabulbah", 'state_id' => 13),
//             array('name' => "Tuzah", 'state_id' => 13),
//             array('name' => "Zaramidin", 'state_id' => 13),
//             array('name' => "Zawiyat Quntash", 'state_id' => 13),
//             array('name' => "al-Baqalitah", 'state_id' => 13),
//             array('name' => "al-Masdur", 'state_id' => 13),
//             array('name' => "al-Muknin", 'state_id' => 13),
//             array('name' => "al-Munastir", 'state_id' => 13),
//             array('name' => "al-Wardanin", 'state_id' => 13),
//             array('name' => "ash-Sharahil", 'state_id' => 13),
//             array('name' => "Firyanah", 'state_id' => 24),
//             array('name' => "Fussanah", 'state_id' => 24),
//             array('name' => "Haydrah", 'state_id' => 24),
//             array('name' => "Jadliyan", 'state_id' => 24),
//             array('name' => "Majal Bal 'Abbas", 'state_id' => 24),
//             array('name' => "Sabibah", 'state_id' => 24),
//             array('name' => "Subaytilah", 'state_id' => 24),
//             array('name' => "Talabat", 'state_id' => 24),
//             array('name' => "Talah", 'state_id' => 24),
//             array('name' => "al-Qasrayn", 'state_id' => 24),
//             array('name' => "'Ayn Jalulah", 'state_id' => 25),
//             array('name' => "Buhajlah", 'state_id' => 25),
//             array('name' => "Haffuz", 'state_id' => 25),
//             array('name' => "Hajib-al-'Ayun", 'state_id' => 25),
//             array('name' => "Manzil Mahidi", 'state_id' => 25),
//             array('name' => "Nasr Allah", 'state_id' => 25),
//             array('name' => "al-'Ala", 'state_id' => 25),
//             array('name' => "al-Qayrawan", 'state_id' => 25),
//             array('name' => "al-Waslatiyah", 'state_id' => 25),
//             array('name' => "as-Subaykhah", 'state_id' => 25),
//             array('name' => "ash-Shabikah", 'state_id' => 25),
//             array('name' => "ash-Sharardah", 'state_id' => 25),
//  );
//         DB::table('cities')->insert($cities);
//     }
// }